WHITE = '#f2f0ec'
BLACK = '#515151'
RED = '#f2777a'
BLUE = '#6699cc'
GREEN = '#33cc66'
YELLOW = '#ffcc66'

c.colors.completion.category.bg = WHITE
c.colors.completion.category.border.bottom = WHITE
c.colors.completion.category.border.top = BLACK
c.colors.completion.category.fg = BLACK
c.colors.completion.even.bg = WHITE
c.colors.completion.fg = [RED, BLACK, BLACK]
c.colors.completion.item.selected.bg = BLACK
c.colors.completion.item.selected.border.bottom = WHITE
c.colors.completion.item.selected.border.top = WHITE
c.colors.completion.item.selected.fg = WHITE
c.colors.completion.item.selected.match.fg = GREEN
c.colors.completion.match.fg = GREEN
c.colors.completion.odd.bg = WHITE
c.colors.completion.scrollbar.bg = WHITE
c.colors.completion.scrollbar.fg = BLACK
c.colors.statusbar.command.bg = WHITE
c.colors.statusbar.command.fg = BLUE
c.colors.statusbar.command.private.bg = BLUE
c.colors.statusbar.command.private.fg = WHITE
c.colors.statusbar.insert.bg = WHITE
c.colors.statusbar.insert.fg = GREEN
c.colors.statusbar.normal.bg = WHITE
c.colors.statusbar.normal.fg = BLACK
c.colors.statusbar.private.bg = BLACK
c.colors.statusbar.private.fg = WHITE
c.colors.statusbar.url.error.fg = RED
c.colors.statusbar.url.fg = BLACK
c.colors.statusbar.url.success.http.fg = BLACK
c.colors.statusbar.url.success.https.fg = GREEN
c.colors.statusbar.url.warn.fg = YELLOW
c.colors.tabs.bar.bg = WHITE
c.colors.tabs.even.bg = WHITE
c.colors.tabs.even.fg = BLACK
c.colors.tabs.indicator.error = RED
c.colors.tabs.indicator.start = BLACK
c.colors.tabs.indicator.stop = GREEN
c.colors.tabs.odd.bg = WHITE
c.colors.tabs.odd.fg = BLACK
c.colors.tabs.selected.even.bg = WHITE
c.colors.tabs.selected.even.fg = GREEN
c.colors.tabs.selected.odd.bg = WHITE
c.colors.tabs.selected.odd.fg = GREEN
c.colors.webpage.bg = WHITE
c.fonts.default_size = '8pt'
c.statusbar.position = 'top'
c.tabs.indicator.width = 10
c.tabs.max_width = 200
c.url.default_page = 'about:blank'
c.url.searchengines = {
	'DEFAULT': 'https://duckduckgo.com/?q={}',
	'REDDIT': 'https://old.reddit.com/r/{}',
	'WIKI': 'https://en.wikipedia.org/wiki/{}'
}
c.url.start_pages = ['about:blank']
c.zoom.default = '90%'
